from .animal import Animal
from .frog import Frog
from .toad import Toad
from .gator import Gator
from .turtle import Turtle
from .snake import Snake
from .catfish import Catfish
from .whale import Whale
from .shark import Shark
from .seal import Seal
from .dolphin import Dolphin
from .llama import Llama
from .dog import Dog
from .goat import Goat
from .rabbit import Rabbit
from .elephant import Elephant